## static_languages
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ES' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ET' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ID' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='II' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='JA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='JV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Luba-Katanga' WHERE lg_iso_2='LU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ML' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Bokmål' WHERE lg_iso_2='NB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Nord-ndebele' WHERE lg_iso_2='ND' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Sør-ndebele' WHERE lg_iso_2='NR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='QU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SQ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ST' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='WA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='WO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='XH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='YI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='YO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='HK';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='CN';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='BR';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='CA';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='PH';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='ME';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='CH';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='AT';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='US';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='GB';

DROP TABLE IF EXISTS static_languages_locals;
CREATE TABLE static_languages_locals (
  uid int(11) NOT NULL auto_increment,
  pid int(11) DEFAULT '0' NOT NULL,
  deleted smallint(6) DEFAULT '0' NOT NULL,
  ll_iso639 varchar(50) DEFAULT '' NOT NULL,
  ll_iso639_locale varchar(50) DEFAULT '' NOT NULL,
  ll_iso639_name varchar(50) DEFAULT '' NOT NULL,
  PRIMARY KEY (uid),
  KEY iso639 (ll_iso639)
);

INSERT INTO static_languages_locals VALUES ('1', '0', '0', 'af', 'af_NA', 'Afrikaans (Namibia)');
INSERT INTO static_languages_locals VALUES ('2', '0', '0', 'af', 'af_ZA', 'Afrikaans (Südafrika)');
INSERT INTO static_languages_locals VALUES ('3', '0', '0', 'ak', 'ak_GH', 'Akan (Ghana)');
INSERT INTO static_languages_locals VALUES ('4', '0', '0', 'am', 'am_ET', 'Amharisch (Äthiopien)');
INSERT INTO static_languages_locals VALUES ('5', '0', '0', 'ar', 'ar_100', 'Arabisch (Welt)');
INSERT INTO static_languages_locals VALUES ('6', '0', '0', 'ar', 'ar_AE', 'Arabisch (Vereinigte Arabische Emirate)');
INSERT INTO static_languages_locals VALUES ('7', '0', '0', 'ar', 'ar_BH', 'Arabisch (Bahrain)');
INSERT INTO static_languages_locals VALUES ('8', '0', '0', 'ar', 'ar_DZ', 'Arabisch (Algerien)');
INSERT INTO static_languages_locals VALUES ('9', '0', '0', 'ar', 'ar_EG', 'Arabisch (Ägypten)');
INSERT INTO static_languages_locals VALUES ('10', '0', '0', 'ar', 'ar_IQ', 'Arabisch (Irak)');
INSERT INTO static_languages_locals VALUES ('11', '0', '0', 'ar', 'ar_JQ', 'Arabisch (Jordanien)');
INSERT INTO static_languages_locals VALUES ('12', '0', '0', 'ar', 'ar_KW', 'Arabisch (Kuwait)');
INSERT INTO static_languages_locals VALUES ('13', '0', '0', 'ar', 'ar_LB', 'Arabisch (Libanon)');
INSERT INTO static_languages_locals VALUES ('14', '0', '0', 'ar', 'ar_LY', 'Arabisch (Libyen)');
INSERT INTO static_languages_locals VALUES ('15', '0', '0', 'ar', 'ar_MA', 'Arabisch (Marokko)');
INSERT INTO static_languages_locals VALUES ('16', '0', '0', 'ar', 'ar_OM', 'Arabisch (Oman)');
INSERT INTO static_languages_locals VALUES ('17', '0', '0', 'ar', 'ar_QA', 'Arabisch (Katar)');
INSERT INTO static_languages_locals VALUES ('18', '0', '0', 'ar', 'ar_SA', 'Arabisch (Saudi-Arabien)');
INSERT INTO static_languages_locals VALUES ('19', '0', '0', 'ar', 'ar_SD', 'Arabisch (Sudan)');
INSERT INTO static_languages_locals VALUES ('20', '0', '0', 'ar', 'ar_SY', 'Arabisch (Syrien)');
INSERT INTO static_languages_locals VALUES ('21', '0', '0', 'ar', 'ar_TN', 'Arabisch (Tunesien)');
INSERT INTO static_languages_locals VALUES ('22', '0', '0', 'ar', 'ar_YE', 'Arabisch (Jemen)');
INSERT INTO static_languages_locals VALUES ('23', '0', '0', 'as', 'as_IN', 'Assamesisch (Indien)');
INSERT INTO static_languages_locals VALUES ('24', '0', '0', 'az', 'az_Cyrl', 'Aserbaidschanisch (Kyrillisch)');
INSERT INTO static_languages_locals VALUES ('25', '0', '0', 'az', 'az_Cyrl_AZ', 'Aserbaidschanisch (Kyrillisch, Aserbaidschan)');
INSERT INTO static_languages_locals VALUES ('26', '0', '0', 'az', 'az_Latn', 'Aserbaidschanisch (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('27', '0', '0', 'az', 'az_Latn_AZ', 'Aserbaidschanisch (Lateinisch, Aserbaidschan)');
INSERT INTO static_languages_locals VALUES ('28', '0', '0', 'bas', 'bas_CM', 'Basaa-Sprache (Kamerun)');
INSERT INTO static_languages_locals VALUES ('29', '0', '0', 'be', 'be_BY', 'Weißrussisch (Belarus)');
INSERT INTO static_languages_locals VALUES ('30', '0', '0', 'bem', 'bem_ZM', 'Bemba-Sprache (Sambia)');
INSERT INTO static_languages_locals VALUES ('31', '0', '0', 'bg', 'bg_BG', 'Bulgarisch (Bulgarien)');
INSERT INTO static_languages_locals VALUES ('32', '0', '0', 'bm', 'bm_ML', 'Bambara-Sprache (Mali)');
INSERT INTO static_languages_locals VALUES ('33', '0', '0', 'bn', 'bn_BD', 'Bengalisch (Bangladesch)');
INSERT INTO static_languages_locals VALUES ('34', '0', '0', 'bn', 'bn_IN', 'Bengalisch (Indien)');
INSERT INTO static_languages_locals VALUES ('35', '0', '0', 'bo', 'bo_CN', 'Tibetisch (China)');
INSERT INTO static_languages_locals VALUES ('36', '0', '0', 'bo', 'bo_IN', 'Tibetisch (Indien)');
INSERT INTO static_languages_locals VALUES ('37', '0', '0', 'br', 'br_FR', 'Bretonisch (Frankreich)');
INSERT INTO static_languages_locals VALUES ('38', '0', '0', 'bs', 'bs_BA', 'Bosnisch (Bosnien und Herzegowina)');
INSERT INTO static_languages_locals VALUES ('39', '0', '0', 'ca', 'ca_ES', 'Katalanisch (Spanien)');
INSERT INTO static_languages_locals VALUES ('40', '0', '0', 'chr', 'chr_US', 'Cherokee (Vereinigte Staaten)');
INSERT INTO static_languages_locals VALUES ('41', '0', '0', 'cs', 'cs_CZ', 'Tschechisch (Tschechische Republik)');
INSERT INTO static_languages_locals VALUES ('42', '0', '0', 'cy', 'cy_GB', 'Walisisch (Vereinigtes Königreich)');
INSERT INTO static_languages_locals VALUES ('43', '0', '0', 'da', 'da_DK', 'Dänisch (Dänemark)');
INSERT INTO static_languages_locals VALUES ('44', '0', '0', 'de', 'de_AT', 'Deutsch (Österreich)');
INSERT INTO static_languages_locals VALUES ('45', '0', '0', 'de', 'de_BE', 'Deutsch (Belgien)');
INSERT INTO static_languages_locals VALUES ('46', '0', '0', 'de', 'de_CH', 'Deutsch (Schweiz)');
INSERT INTO static_languages_locals VALUES ('47', '0', '0', 'de', 'de_DE', 'Deutsch (Deutschland)');
INSERT INTO static_languages_locals VALUES ('48', '0', '0', 'de', 'de_LI', 'Deutsch (Liechtenstein)');
INSERT INTO static_languages_locals VALUES ('49', '0', '0', 'de', 'de_LU', 'Deutsch (Luxemburg)');
INSERT INTO static_languages_locals VALUES ('50', '0', '0', 'dua', 'dua_CM', 'Duala (Kamerun)');
INSERT INTO static_languages_locals VALUES ('51', '0', '0', 'ee', 'ee_GH', 'Ewe-Sprache (Ghana)');
INSERT INTO static_languages_locals VALUES ('52', '0', '0', 'ee', 'ee_TG', 'Ewe-Sprache (Togo)');
INSERT INTO static_languages_locals VALUES ('53', '0', '0', 'el', 'el_CY', 'Griechisch (Zypern)');
INSERT INTO static_languages_locals VALUES ('54', '0', '0', 'ek', 'ek_GR', 'Griechisch (Griechenland)');
INSERT INTO static_languages_locals VALUES ('55', '0', '0', 'en', 'en_AS', 'Englisch (Amerikanisch-Samoa)');
INSERT INTO static_languages_locals VALUES ('56', '0', '0', 'en', 'en_AU', 'Englisch (Australien)');
INSERT INTO static_languages_locals VALUES ('57', '0', '0', 'en', 'en_BB', 'Englisch (Barbados)');
INSERT INTO static_languages_locals VALUES ('58', '0', '0', 'en', 'en_BE', 'Englisch (Belgien');
INSERT INTO static_languages_locals VALUES ('59', '0', '0', 'en', 'en_BM', 'Englisch (Bermuda)');
INSERT INTO static_languages_locals VALUES ('60', '0', '0', 'en', 'en_BW', 'Englisch (Botsuana)');
INSERT INTO static_languages_locals VALUES ('61', '0', '0', 'en', 'en_BZ', 'Englisch (Belize)');
INSERT INTO static_languages_locals VALUES ('62', '0', '0', 'en', 'en_CA', 'Englisch (Kanada)');
INSERT INTO static_languages_locals VALUES ('63', '0', '0', 'en', 'en_GB', 'Englisch (Vereinigtes Königreich)');
