## static_languages
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='AZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='BS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='CY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ES' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ET' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='GV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='HZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ID' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='II' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='IU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='JA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='JV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='KY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Luba-Katanga' WHERE lg_iso_2='LU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='LV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ML' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='MY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Bokmål' WHERE lg_iso_2='NB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Nord-ndebele' WHERE lg_iso_2='ND' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='Sør-ndebele' WHERE lg_iso_2='NR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='NY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='OS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='QU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='RW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SQ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ST' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='UZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='VO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='WA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='WO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='XH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='YI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='YO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='HK';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='CN';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='BR';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='CA';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='PH';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='ME';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='CH';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='AT';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='US';
UPDATE static_languages SET lg_iso639='' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='GB';

DROP TABLE IF EXISTS static_languages_locals;
CREATE TABLE static_languages_locals (
  uid int(11) NOT NULL auto_increment,
  pid int(11) DEFAULT '0' NOT NULL,
  deleted smallint(6) DEFAULT '0' NOT NULL,
  ll_iso639 varchar(50) DEFAULT '' NOT NULL,
  ll_iso639_locale varchar(50) DEFAULT '' NOT NULL,
  ll_iso639_name varchar(50) DEFAULT '' NOT NULL,
  PRIMARY KEY (uid),
  KEY iso639 (ll_iso639)
);

INSERT INTO static_languages_locals VALUES ('1', '0', '0', 'af', 'af_NA', 'Afrikaans (Namibia)');
INSERT INTO static_languages_locals VALUES ('2', '0', '0', 'af', 'af_ZA', 'Afrikaans (Südafrika)');
INSERT INTO static_languages_locals VALUES ('3', '0', '0', 'ak', 'ak_GH', 'Akan (Ghana)');
INSERT INTO static_languages_locals VALUES ('4', '0', '0', 'am', 'am_ET', 'Amharisch (Äthiopien)');
INSERT INTO static_languages_locals VALUES ('5', '0', '0', 'ar', 'ar_001', 'Arabisch (Welt)');
INSERT INTO static_languages_locals VALUES ('6', '0', '0', 'ar', 'ar_AE', 'Arabisch (Vereinigte Arabische Emirate)');
INSERT INTO static_languages_locals VALUES ('7', '0', '0', 'ar', 'ar_BH', 'Arabisch (Bahrain)');
INSERT INTO static_languages_locals VALUES ('8', '0', '0', 'ar', 'ar_DZ', 'Arabisch (Algerien)');
INSERT INTO static_languages_locals VALUES ('9', '0', '0', 'ar', 'ar_EG', 'Arabisch (Ägypten)');
INSERT INTO static_languages_locals VALUES ('10', '0', '0', 'ar', 'ar_IQ', 'Arabisch (Irak)');
INSERT INTO static_languages_locals VALUES ('11', '0', '0', 'ar', 'ar_JO', 'Arabisch (Jordanien)');
INSERT INTO static_languages_locals VALUES ('12', '0', '0', 'ar', 'ar_KW', 'Arabisch (Kuwait)');
INSERT INTO static_languages_locals VALUES ('13', '0', '0', 'ar', 'ar_LB', 'Arabisch (Libanon)');
INSERT INTO static_languages_locals VALUES ('14', '0', '0', 'ar', 'ar_LY', 'Arabisch (Libyen)');
INSERT INTO static_languages_locals VALUES ('15', '0', '0', 'ar', 'ar_MA', 'Arabisch (Marokko)');
INSERT INTO static_languages_locals VALUES ('16', '0', '0', 'ar', 'ar_OM', 'Arabisch (Oman)');
INSERT INTO static_languages_locals VALUES ('17', '0', '0', 'ar', 'ar_QA', 'Arabisch (Katar)');
INSERT INTO static_languages_locals VALUES ('18', '0', '0', 'ar', 'ar_SA', 'Arabisch (Saudi-Arabien)');
INSERT INTO static_languages_locals VALUES ('19', '0', '0', 'ar', 'ar_SD', 'Arabisch (Sudan)');
INSERT INTO static_languages_locals VALUES ('20', '0', '0', 'ar', 'ar_SY', 'Arabisch (Syrien)');
INSERT INTO static_languages_locals VALUES ('21', '0', '0', 'ar', 'ar_TN', 'Arabisch (Tunesien)');
INSERT INTO static_languages_locals VALUES ('22', '0', '0', 'ar', 'ar_YE', 'Arabisch (Jemen)');
INSERT INTO static_languages_locals VALUES ('23', '0', '0', 'as', 'as_IN', 'Assamesisch (Indien)');
INSERT INTO static_languages_locals VALUES ('24', '0', '0', 'az', 'az_Cyrl', 'Aserbaidschanisch (Kyrillisch)');
INSERT INTO static_languages_locals VALUES ('25', '0', '0', 'az', 'az_Cyrl_AZ', 'Aserbaidschanisch (Kyrillisch, Aserbaidschan)');
INSERT INTO static_languages_locals VALUES ('26', '0', '0', 'az', 'az_Latn', 'Aserbaidschanisch (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('27', '0', '0', 'az', 'az_Latn_AZ', 'Aserbaidschanisch (Lateinisch, Aserbaidschan)');
INSERT INTO static_languages_locals VALUES ('28', '0', '0', 'bas', 'bas_CM', 'Basaa-Sprache (Kamerun)');
INSERT INTO static_languages_locals VALUES ('29', '0', '0', 'be', 'be_BY', 'Weißrussisch (Belarus)');
INSERT INTO static_languages_locals VALUES ('30', '0', '0', 'bem', 'bem_ZM', 'Bemba-Sprache (Sambia)');
INSERT INTO static_languages_locals VALUES ('31', '0', '0', 'bg', 'bg_BG', 'Bulgarisch (Bulgarien)');
INSERT INTO static_languages_locals VALUES ('32', '0', '0', 'bm', 'bm_ML', 'Bambara-Sprache (Mali)');
INSERT INTO static_languages_locals VALUES ('33', '0', '0', 'bn', 'bn_BD', 'Bengalisch (Bangladesch)');
INSERT INTO static_languages_locals VALUES ('34', '0', '0', 'bn', 'bn_IN', 'Bengalisch (Indien)');
INSERT INTO static_languages_locals VALUES ('35', '0', '0', 'bo', 'bo_CN', 'Tibetisch (China)');
INSERT INTO static_languages_locals VALUES ('36', '0', '0', 'bo', 'bo_IN', 'Tibetisch (Indien)');
INSERT INTO static_languages_locals VALUES ('37', '0', '0', 'br', 'br_FR', 'Bretonisch (Frankreich)');
INSERT INTO static_languages_locals VALUES ('38', '0', '0', 'bs', 'bs_BA', 'Bosnisch (Bosnien und Herzegowina)');
INSERT INTO static_languages_locals VALUES ('39', '0', '0', 'ca', 'ca_ES', 'Katalanisch (Spanien)');
INSERT INTO static_languages_locals VALUES ('40', '0', '0', 'chr', 'chr_US', 'Cherokee (Vereinigte Staaten)');
INSERT INTO static_languages_locals VALUES ('41', '0', '0', 'cs', 'cs_CZ', 'Tschechisch (Tschechische Republik)');
INSERT INTO static_languages_locals VALUES ('42', '0', '0', 'cy', 'cy_GB', 'Walisisch (Vereinigtes Königreich)');
INSERT INTO static_languages_locals VALUES ('43', '0', '0', 'da', 'da_DK', 'Dänisch (Dänemark)');
INSERT INTO static_languages_locals VALUES ('44', '0', '0', 'de', 'de_AT', 'Deutsch (Österreich)');
INSERT INTO static_languages_locals VALUES ('45', '0', '0', 'de', 'de_BE', 'Deutsch (Belgien)');
INSERT INTO static_languages_locals VALUES ('46', '0', '0', 'de', 'de_CH', 'Deutsch (Schweiz)');
INSERT INTO static_languages_locals VALUES ('47', '0', '0', 'de', 'de_DE', 'Deutsch (Deutschland)');
INSERT INTO static_languages_locals VALUES ('48', '0', '0', 'de', 'de_LI', 'Deutsch (Liechtenstein)');
INSERT INTO static_languages_locals VALUES ('49', '0', '0', 'de', 'de_LU', 'Deutsch (Luxemburg)');
INSERT INTO static_languages_locals VALUES ('50', '0', '0', 'dua', 'dua_CM', 'Duala (Kamerun)');
INSERT INTO static_languages_locals VALUES ('51', '0', '0', 'ee', 'ee_GH', 'Ewe-Sprache (Ghana)');
INSERT INTO static_languages_locals VALUES ('52', '0', '0', 'ee', 'ee_TG', 'Ewe-Sprache (Togo)');
INSERT INTO static_languages_locals VALUES ('53', '0', '0', 'el', 'el_CY', 'Griechisch (Zypern)');
INSERT INTO static_languages_locals VALUES ('54', '0', '0', 'ek', 'el_GR', 'Griechisch (Griechenland)');
INSERT INTO static_languages_locals VALUES ('55', '0', '0', 'en', 'en_AS', 'Englisch (Amerikanisch-Samoa)');
INSERT INTO static_languages_locals VALUES ('56', '0', '0', 'en', 'en_AU', 'Englisch (Australien)');
INSERT INTO static_languages_locals VALUES ('57', '0', '0', 'en', 'en_BB', 'Englisch (Barbados)');
INSERT INTO static_languages_locals VALUES ('58', '0', '0', 'en', 'en_BE', 'Englisch (Belgien)');
INSERT INTO static_languages_locals VALUES ('59', '0', '0', 'en', 'en_BM', 'Englisch (Bermuda)');
INSERT INTO static_languages_locals VALUES ('60', '0', '0', 'en', 'en_BW', 'Englisch (Botsuana)');
INSERT INTO static_languages_locals VALUES ('61', '0', '0', 'en', 'en_BZ', 'Englisch (Belize)');
INSERT INTO static_languages_locals VALUES ('62', '0', '0', 'en', 'en_CA', 'Englisch (Kanada)');
INSERT INTO static_languages_locals VALUES ('63', '0', '0', 'en', 'en_GB', 'Englisch (Vereinigtes Königreich)');
INSERT INTO static_languages_locals VALUES ('64', '0', '0', 'en', 'en-GU', 'Englisch (Guam)');
INSERT INTO static_languages_locals VALUES ('65', '0', '0', 'en', 'en-GY', 'Englisch (Guyana)');
INSERT INTO static_languages_locals VALUES ('66', '0', '0', 'en', 'en-HK', 'Englisch (Sonderverwaltungszone Hongkong)');
INSERT INTO static_languages_locals VALUES ('67', '0', '0', 'en', 'en-IE', 'Englisch (Irland)');
INSERT INTO static_languages_locals VALUES ('68', '0', '0', 'en', 'en-IN', 'Englisch (Indien)');
INSERT INTO static_languages_locals VALUES ('69', '0', '0', 'en', 'en-JM', 'Englisch (Jamaika)');
INSERT INTO static_languages_locals VALUES ('70', '0', '0', 'en', 'en-MH', 'Englisch (Marshallinseln)');
INSERT INTO static_languages_locals VALUES ('71', '0', '0', 'en', 'en-MP', 'Englisch (Nördliche Marianen)');
INSERT INTO static_languages_locals VALUES ('72', '0', '0', 'en', 'en-MT', 'Englisch (Malta)');
INSERT INTO static_languages_locals VALUES ('73', '0', '0', 'en', 'en-MU', 'Englisch (Mauritius)');
INSERT INTO static_languages_locals VALUES ('74', '0', '0', 'en', 'en-NA', 'Englisch (Namibia)');
INSERT INTO static_languages_locals VALUES ('75', '0', '0', 'en', 'en-NZ', 'Englisch (Neuseeland)');
INSERT INTO static_languages_locals VALUES ('76', '0', '0', 'en', 'en-PH', 'Englisch (Philippinen)');
INSERT INTO static_languages_locals VALUES ('77', '0', '0', 'en', 'en-PK', 'Englisch (Pakistan)');
INSERT INTO static_languages_locals VALUES ('78', '0', '0', 'en', 'en-SG', 'Englisch (Singapur)');
INSERT INTO static_languages_locals VALUES ('79', '0', '0', 'en', 'en-TT', 'Englisch (Trinidad und Tobago)');
INSERT INTO static_languages_locals VALUES ('80', '0', '0', 'en', 'en-UM', 'Englisch (Amerikanisch-Ozeanien)');
INSERT INTO static_languages_locals VALUES ('81', '0', '0', 'en', 'en-US', 'Englisch (Vereinigte Staaten)');
INSERT INTO static_languages_locals VALUES ('82', '0', '0', 'en', 'en-US-POSIX', 'Englisch (Vereinigte Staaten, Posix)');
INSERT INTO static_languages_locals VALUES ('83', '0', '0', 'en', 'en-VI', 'Englisch (Amerikanische Jungferninseln)');
INSERT INTO static_languages_locals VALUES ('84', '0', '0', 'en', 'en-ZA', 'Englisch (Südafrika)');
INSERT INTO static_languages_locals VALUES ('85', '0', '0', 'en', 'en-ZW', 'Englisch (Simbabwe)');
INSERT INTO static_languages_locals VALUES ('86', '0', '0', 'es', 'es-419', 'Spanisch (Lateinamerika)');
INSERT INTO static_languages_locals VALUES ('87', '0', '0', 'es', 'es-AR', 'Spanisch (Argentinien)');
INSERT INTO static_languages_locals VALUES ('88', '0', '0', 'es', 'es-BO', 'Spanisch (Bolivien)');
INSERT INTO static_languages_locals VALUES ('89', '0', '0', 'es', 'es-CL', 'Spanisch (Chile)');
INSERT INTO static_languages_locals VALUES ('90', '0', '0', 'es', 'es-CO', 'Spanisch (Kolumbien)');
INSERT INTO static_languages_locals VALUES ('91', '0', '0', 'es', 'es-CR', 'Spanisch (Costa Rica)');
INSERT INTO static_languages_locals VALUES ('92', '0', '0', 'es', 'es-DO', 'Spanisch (Dominikanische Republik)');
INSERT INTO static_languages_locals VALUES ('93', '0', '0', 'es', 'es-EC', 'Spanisch (Ecuador)');
INSERT INTO static_languages_locals VALUES ('94', '0', '0', 'es', 'es-ES', 'Spanisch (Spanien)');
INSERT INTO static_languages_locals VALUES ('95', '0', '0', 'es', 'es-GQ', 'Spanisch (Äquatorialguinea)');
INSERT INTO static_languages_locals VALUES ('96', '0', '0', 'es', 'es-GT', 'Spanisch (Guatemala)');
INSERT INTO static_languages_locals VALUES ('97', '0', '0', 'es', 'es-HN', 'Spanisch (Honduras)');
INSERT INTO static_languages_locals VALUES ('98', '0', '0', 'es', 'es-MX', 'Spanisch (Mexiko)');
INSERT INTO static_languages_locals VALUES ('99', '0', '0', 'es', 'es-NI', 'Spanisch (Nicaragua)');
INSERT INTO static_languages_locals VALUES ('100', '0', '0', 'es', 'es-PA', 'Spanisch (Panama)');
INSERT INTO static_languages_locals VALUES ('101', '0', '0', 'es', 'es-PE', 'Spanisch (Peru)');
INSERT INTO static_languages_locals VALUES ('102', '0', '0', 'es', 'es-PR', 'Spanisch (Puerto Rico)');
INSERT INTO static_languages_locals VALUES ('103', '0', '0', 'es', 'es-PY', 'Spanisch (Paraguay)');
INSERT INTO static_languages_locals VALUES ('104', '0', '0', 'es', 'es-SV', 'Spanisch (El Salvador)');
INSERT INTO static_languages_locals VALUES ('105', '0', '0', 'es', 'es-US', 'Spanisch (Vereinigte Staaten)');
INSERT INTO static_languages_locals VALUES ('106', '0', '0', 'es', 'es-UY', 'Spanisch (Uruguay)');
INSERT INTO static_languages_locals VALUES ('107', '0', '0', 'es', 'es-VE', 'Spanisch (Venezuela)');
INSERT INTO static_languages_locals VALUES ('108', '0', '0', 'et', 'et-EE', 'Estnisch (Estland)');
INSERT INTO static_languages_locals VALUES ('109', '0', '0', 'eu', 'eu-ES', 'Baskisch (Spanien)');
INSERT INTO static_languages_locals VALUES ('110', '0', '0', 'ewo', 'ewo-CM', 'Ewondo (Kamerun)');
INSERT INTO static_languages_locals VALUES ('111', '0', '0', 'fa', 'fa-AF', 'Persisch (Afghanistan)');
INSERT INTO static_languages_locals VALUES ('112', '0', '0', 'fa', 'fa-IR', 'Persisch (Iran)');
INSERT INTO static_languages_locals VALUES ('113', '0', '0', 'ff', 'ff-SN', 'Ful (Senegal)');
INSERT INTO static_languages_locals VALUES ('114', '0', '0', 'fi', 'fi-FI', 'Finnisch (Finnland)');
INSERT INTO static_languages_locals VALUES ('115', '0', '0', 'fo', 'fo-FO', 'Färöisch (Färöer)');
INSERT INTO static_languages_locals VALUES ('116', '0', '0', 'fr', 'fr-BE', 'Französisch (Belgien)');
INSERT INTO static_languages_locals VALUES ('117', '0', '0', 'fr', 'fr-BF', 'Französisch (Burkina Faso)');
INSERT INTO static_languages_locals VALUES ('118', '0', '0', 'fr', 'fr-BI', 'Französisch (Burundi)');
INSERT INTO static_languages_locals VALUES ('119', '0', '0', 'fr', 'fr-BJ', 'Französisch (Benin)');
INSERT INTO static_languages_locals VALUES ('120', '0', '0', 'fr', 'fr-BL', 'Französisch (St. Barthélemy)');
INSERT INTO static_languages_locals VALUES ('121', '0', '0', 'fr', 'fr-CA', 'Französisch (Kanada)');
INSERT INTO static_languages_locals VALUES ('122', '0', '0', 'fr', 'fr-CD', 'Französisch (Kongo-Kinshasa)');
INSERT INTO static_languages_locals VALUES ('123', '0', '0', 'fr', 'fr-CF', 'Französisch (Zentralafrikanische Republik)');
INSERT INTO static_languages_locals VALUES ('124', '0', '0', 'fr', 'fr-CG', 'Französisch (Kongo-Brazzaville)');
INSERT INTO static_languages_locals VALUES ('125', '0', '0', 'fr', 'fr-CH', 'Französisch (Schweiz)');
INSERT INTO static_languages_locals VALUES ('126', '0', '0', 'fr', 'fr-CI', 'Französisch (Côte d’Ivoire)');
INSERT INTO static_languages_locals VALUES ('127', '0', '0', 'fr', 'fr-CM', 'Französisch (Kamerun)');
INSERT INTO static_languages_locals VALUES ('128', '0', '0', 'fr', 'fr-DJ', 'Französisch (Dschibuti)');
INSERT INTO static_languages_locals VALUES ('129', '0', '0', 'fr', 'fr-FR', 'Französisch (Frankreich)');
INSERT INTO static_languages_locals VALUES ('130', '0', '0', 'fr', 'fr-GA', 'Französisch (Gabun)');
INSERT INTO static_languages_locals VALUES ('131', '0', '0', 'fr', 'fr-GF', 'Französisch (Französisch-Guayana)');
INSERT INTO static_languages_locals VALUES ('132', '0', '0', 'fr', 'fr-GN', 'Französisch (Guinea)');
INSERT INTO static_languages_locals VALUES ('133', '0', '0', 'fr', 'fr-GP', 'Französisch (Guadeloupe)');
INSERT INTO static_languages_locals VALUES ('134', '0', '0', 'fr', 'fr-GQ', 'Französisch (Äquatorialguinea)');
INSERT INTO static_languages_locals VALUES ('135', '0', '0', 'fr', 'fr-KM', 'Französisch (Komoren)');
INSERT INTO static_languages_locals VALUES ('136', '0', '0', 'fr', 'fr-LU', 'Französisch (Luxemburg)');
INSERT INTO static_languages_locals VALUES ('137', '0', '0', 'fr', 'fr-MC', 'Französisch (Monaco)');
INSERT INTO static_languages_locals VALUES ('138', '0', '0', 'fr', 'fr-MF', 'Französisch (St. Martin)');
INSERT INTO static_languages_locals VALUES ('139', '0', '0', 'fr', 'fr-MG', 'Französisch (Madagaskar)');
INSERT INTO static_languages_locals VALUES ('140', '0', '0', 'fr', 'fr-ML', 'Französisch (Mali)');
INSERT INTO static_languages_locals VALUES ('141', '0', '0', 'fr', 'fr-MQ', 'Französisch (Martinique)');
INSERT INTO static_languages_locals VALUES ('142', '0', '0', 'fr', 'fr-NE', 'Französisch (Niger)');
INSERT INTO static_languages_locals VALUES ('143', '0', '0', 'fr', 'fr-RE', 'Französisch (Réunion)');
INSERT INTO static_languages_locals VALUES ('144', '0', '0', 'fr', 'fr-RW', 'Französisch (Ruanda)');
INSERT INTO static_languages_locals VALUES ('145', '0', '0', 'fr', 'fr-SN', 'Französisch (Senegal)');
INSERT INTO static_languages_locals VALUES ('146', '0', '0', 'fr', 'fr-TD', 'Französisch (Tschad)');
INSERT INTO static_languages_locals VALUES ('147', '0', '0', 'fr', 'fr-TG', 'Französisch (Togo)');
INSERT INTO static_languages_locals VALUES ('148', '0', '0', 'fr', 'fr-YT', 'Französisch (Mayotte)');
INSERT INTO static_languages_locals VALUES ('149', '0', '0', 'ga', 'ga-IE', 'Irisch (Irland)');
INSERT INTO static_languages_locals VALUES ('150', '0', '0', 'gl', 'gl-ES', 'Galizisch (Spanien)');
INSERT INTO static_languages_locals VALUES ('151', '0', '0', 'gu', 'gu-IN', 'Gujarati (Indien)');
INSERT INTO static_languages_locals VALUES ('152', '0', '0', 'gv', 'gv-GB', 'Manx (Vereinigtes Königreich)');
INSERT INTO static_languages_locals VALUES ('153', '0', '0', 'ha', 'ha-Latn', 'Hausa (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('154', '0', '0', 'ha', 'ha-Latn-GH', 'Hausa (Lateinisch, Ghana)');
INSERT INTO static_languages_locals VALUES ('155', '0', '0', 'ha', 'ha-Latn-NE', 'Hausa (Lateinisch, Niger)');
INSERT INTO static_languages_locals VALUES ('156', '0', '0', 'ha', 'ha-Latn-NG', 'Hausa (Lateinisch, Nigeria)');
INSERT INTO static_languages_locals VALUES ('157', '0', '0', 'haw', 'haw-US', 'Hawaiisch (Vereinigte Staaten)');
INSERT INTO static_languages_locals VALUES ('158', '0', '0', 'he', 'he-IL', 'Hebräisch (Israel)');
INSERT INTO static_languages_locals VALUES ('159', '0', '0', 'hi', 'hi-IN', 'Hindi (Indien)');
INSERT INTO static_languages_locals VALUES ('160', '0', '0', 'hr', 'hr-HR', 'Kroatisch (Kroatien)');
INSERT INTO static_languages_locals VALUES ('161', '0', '0', 'hu', 'hu-HU', 'Ungarisch (Ungarn)');
INSERT INTO static_languages_locals VALUES ('162', '0', '0', 'hy', 'hy-AM', 'Armenisch (Armenien)');
INSERT INTO static_languages_locals VALUES ('163', '0', '0', 'id', 'id-ID', 'Indonesisch (Indonesien)');
INSERT INTO static_languages_locals VALUES ('164', '0', '0', 'ig', 'ig-NG', 'Igbo-Sprache (Nigeria)');
INSERT INTO static_languages_locals VALUES ('165', '0', '0', 'ii', 'ii-CN', 'Sichuan Yi (China)');
INSERT INTO static_languages_locals VALUES ('166', '0', '0', 'is', 'is-IS', 'Isländisch (Island)');
INSERT INTO static_languages_locals VALUES ('167', '0', '0', 'it', 'it-CH', 'Italienisch (Schweiz)');
INSERT INTO static_languages_locals VALUES ('168', '0', '0', 'it', 'it-IT', 'Italienisch (Italien)');
INSERT INTO static_languages_locals VALUES ('169', '0', '0', 'ja', 'ja-JP', 'Japanisch (Japan)');
INSERT INTO static_languages_locals VALUES ('170', '0', '0', 'ka', 'ka-GE', 'Georgisch (Georgien)');
INSERT INTO static_languages_locals VALUES ('171', '0', '0', 'kab', 'kab-DZ', 'Kabylisch (Algerien)');
INSERT INTO static_languages_locals VALUES ('172', '0', '0', 'kam', 'kam-KE', 'Kamba (Kenia)');
INSERT INTO static_languages_locals VALUES ('173', '0', '0', 'ki', 'ki-KE', 'Kikuyu-Sprache (Kenia)');
INSERT INTO static_languages_locals VALUES ('174', '0', '0', 'kk', 'kk-Cyrl', 'Kasachisch (Kyrillisch)');
INSERT INTO static_languages_locals VALUES ('175', '0', '0', 'kk', 'kk-Cyrl-KZ', 'Kasachisch (Kyrillisch, Kasachstan)');
INSERT INTO static_languages_locals VALUES ('176', '0', '0', 'kl', 'kl-GL', 'Grönländisch (Grönland)');
INSERT INTO static_languages_locals VALUES ('177', '0', '0', 'km', 'km-KH', 'Kambodschanisch (Kambodscha)');
INSERT INTO static_languages_locals VALUES ('178', '0', '0', 'kn', 'kn-IN', 'Kannada (Indien)');
INSERT INTO static_languages_locals VALUES ('179', '0', '0', 'ko', 'ko-KR', 'Koreanisch (Republik Korea)');
INSERT INTO static_languages_locals VALUES ('180', '0', '0', 'kok', 'kok-IN', 'Konkani (Indien)');
INSERT INTO static_languages_locals VALUES ('181', '0', '0', 'kw', 'kw-GB', 'Kornisch (Vereinigtes Königreich)');
INSERT INTO static_languages_locals VALUES ('182', '0', '0', 'lg', 'lg-UG', 'Ganda-Sprache (Uganda)');
INSERT INTO static_languages_locals VALUES ('183', '0', '0', 'ln', 'ln-CD', 'Lingala (Kongo-Kinshasa)');
INSERT INTO static_languages_locals VALUES ('184', '0', '0', 'ln', 'ln-CG', 'Lingala (Kongo-Brazzaville)');
INSERT INTO static_languages_locals VALUES ('185', '0', '0', 'lt', 'lt-LT', 'Litauisch (Litauen)');
INSERT INTO static_languages_locals VALUES ('186', '0', '0', 'lu', 'lu-CD', 'Luba-Katanga (Kongo-Kinshasa)');
INSERT INTO static_languages_locals VALUES ('187', '0', '0', 'luo', 'luo-KE', 'Luo-Sprache (Kenia)');
INSERT INTO static_languages_locals VALUES ('188', '0', '0', 'lv', 'lv-LV', 'Lettisch (Lettland)');
INSERT INTO static_languages_locals VALUES ('189', '0', '0', 'mas', 'mas-KE', 'Massai-Sprache (Kenia)');
INSERT INTO static_languages_locals VALUES ('190', '0', '0', 'mas', 'mas-TZ', 'Massai-Sprache (Tansania)');
INSERT INTO static_languages_locals VALUES ('191', '0', '0', 'mg', 'mg-MG', 'Malagassi-Sprache (Madagaskar)');
INSERT INTO static_languages_locals VALUES ('192', '0', '0', 'mk', 'mk-MK', 'Mazedonisch (Mazedonien)');
INSERT INTO static_languages_locals VALUES ('193', '0', '0', 'ml', 'ml-IN', 'Malayalam (Indien)');
INSERT INTO static_languages_locals VALUES ('194', '0', '0', 'mr', 'mr-IN', 'Marathi (Indien)');
INSERT INTO static_languages_locals VALUES ('195', '0', '0', 'ms', 'ms-BN', 'Malaiisch (Brunei Darussalam)');
INSERT INTO static_languages_locals VALUES ('196', '0', '0', 'ms', 'ms-MY', 'Malaiisch (Malaysia)');
INSERT INTO static_languages_locals VALUES ('197', '0', '0', 'mt', 'mt-MT', 'Maltesisch (Malta)');
INSERT INTO static_languages_locals VALUES ('198', '0', '0', 'my', 'my-MM', 'Birmanisch (Myanmar)');
INSERT INTO static_languages_locals VALUES ('199', '0', '0', 'nb', 'nb-NO', 'Norwegisch Bokmål (Norwegen)');
INSERT INTO static_languages_locals VALUES ('200', '0', '0', 'nd', 'nd-ZW', 'Nord-Ndebele-Sprache (Simbabwe)');
INSERT INTO static_languages_locals VALUES ('201', '0', '0', 'ne', 'ne-IN', 'Nepalesisch (Indien)');
INSERT INTO static_languages_locals VALUES ('202', '0', '0', 'ne', 'ne-NP', 'Nepalesisch (Nepal)');
INSERT INTO static_languages_locals VALUES ('203', '0', '0', 'nl', 'nl-AW', 'Niederländisch (Aruba)');
INSERT INTO static_languages_locals VALUES ('204', '0', '0', 'nl', 'nl-BE', 'Niederländisch (Belgien)');
INSERT INTO static_languages_locals VALUES ('205', '0', '0', 'nl', 'nl-CW', 'Niederländisch (CW)');
INSERT INTO static_languages_locals VALUES ('206', '0', '0', 'nl', 'nl-NL', 'Niederländisch (Niederlande)');
INSERT INTO static_languages_locals VALUES ('207', '0', '0', 'nl', 'nl-SX', 'Niederländisch (SX)');
INSERT INTO static_languages_locals VALUES ('208', '0', '0', 'nn', 'nn-NO', 'Norwegisch Nynorsk (Norwegen)');
INSERT INTO static_languages_locals VALUES ('209', '0', '0', 'nyn', 'nyn-UG', 'Nyankole (Uganda)');
INSERT INTO static_languages_locals VALUES ('210', '0', '0', 'om', 'om-ET', 'Oromo (Äthiopien)');
INSERT INTO static_languages_locals VALUES ('211', '0', '0', 'om', 'om-KE', 'Oromo (Kenia)');
INSERT INTO static_languages_locals VALUES ('212', '0', '0', 'or', 'or-IN', 'Orija (Indien)');
INSERT INTO static_languages_locals VALUES ('213', '0', '0', 'pa', 'pa-Arab', 'Pandschabisch (Arabisch)');
INSERT INTO static_languages_locals VALUES ('214', '0', '0', 'pa', 'pa-Arab-PK', 'Pandschabisch (Arabisch, Pakistan)');
INSERT INTO static_languages_locals VALUES ('215', '0', '0', 'pa', 'pa-Guru', 'Pandschabisch (Gurmukhi)');
INSERT INTO static_languages_locals VALUES ('216', '0', '0', 'pa', 'pa-Guru-IN', 'Pandschabisch (Gurmukhi, Indien)');
INSERT INTO static_languages_locals VALUES ('217', '0', '0', 'pl', 'pl-PL', 'Polnisch (Polen)');
INSERT INTO static_languages_locals VALUES ('218', '0', '0', 'ps', 'ps-AF', 'Paschtu (Afghanistan)');
INSERT INTO static_languages_locals VALUES ('219', '0', '0', 'pt', 'pt-AO', 'Portugiesisch (Angola)');
INSERT INTO static_languages_locals VALUES ('220', '0', '0', 'pt', 'pt-BR', 'Portugiesisch (Brasilien)');
INSERT INTO static_languages_locals VALUES ('221', '0', '0', 'pt', 'pt-GW', 'Portugiesisch (Guinea-Bissau)');
INSERT INTO static_languages_locals VALUES ('222', '0', '0', 'pt', 'pt-MZ', 'Portugiesisch (Mosambik)');
INSERT INTO static_languages_locals VALUES ('223', '0', '0', 'pt', 'pt-PT', 'Portugiesisch (Portugal)');
INSERT INTO static_languages_locals VALUES ('224', '0', '0', 'pt', 'pt-ST', 'Portugiesisch (São Tomé und Príncipe)');
INSERT INTO static_languages_locals VALUES ('225', '0', '0', 'rm', 'rm-CH', 'Rätoromanisch (Schweiz)');
INSERT INTO static_languages_locals VALUES ('226', '0', '0', 'rn', 'rn-BI', 'Rundi-Sprache (Burundi)');
INSERT INTO static_languages_locals VALUES ('227', '0', '0', 'ro', 'ro-MD', 'Rumänisch (Republik Moldau)');
INSERT INTO static_languages_locals VALUES ('228', '0', '0', 'ro', 'ro-RO', 'Rumänisch (Rumänien)');
INSERT INTO static_languages_locals VALUES ('229', '0', '0', 'ru', 'ru-MD', 'Russisch (Republik Moldau)');
INSERT INTO static_languages_locals VALUES ('230', '0', '0', 'ru', 'ru-RU', 'Russisch (Russische Föderation)');
INSERT INTO static_languages_locals VALUES ('231', '0', '0', 'ru', 'ru-UA', 'Russisch (Ukraine)');
INSERT INTO static_languages_locals VALUES ('232', '0', '0', 'rw', 'rw-RW', 'Ruandisch (Ruanda)');
INSERT INTO static_languages_locals VALUES ('233', '0', '0', 'sg', 'sg-CF', 'Sango (Zentralafrikanische Republik)');
INSERT INTO static_languages_locals VALUES ('234', '0', '0', 'si', 'si-LK', 'Singhalesisch (Sri Lanka)');
INSERT INTO static_languages_locals VALUES ('235', '0', '0', 'sk', 'sk-SK', 'Slowakisch (Slowakei)');
INSERT INTO static_languages_locals VALUES ('236', '0', '0', 'sl', 'sl-SI', 'Slowenisch (Slowenien)');
INSERT INTO static_languages_locals VALUES ('237', '0', '0', 'sn', 'sn-ZW', 'Shona (Simbabwe)');
INSERT INTO static_languages_locals VALUES ('238', '0', '0', 'so', 'so-DJ', 'Somali (Dschibuti)');
INSERT INTO static_languages_locals VALUES ('239', '0', '0', 'so', 'so-ET', 'Somali (Äthiopien)');
INSERT INTO static_languages_locals VALUES ('240', '0', '0', 'so', 'so-KE', 'Somali (Kenia)');
INSERT INTO static_languages_locals VALUES ('241', '0', '0', 'so', 'so-SO', 'Somali (Somalia)');
INSERT INTO static_languages_locals VALUES ('242', '0', '0', 'sq', 'sq-AL', 'Albanisch (Albanien)');
INSERT INTO static_languages_locals VALUES ('243', '0', '0', 'sr', 'sr-Cyrl', 'Serbisch (Kyrillisch)');
INSERT INTO static_languages_locals VALUES ('244', '0', '0', 'sr', 'sr-Cyrl-BA', 'Serbisch (Kyrillisch, Bosnien und Herzegowina)');
INSERT INTO static_languages_locals VALUES ('245', '0', '0', 'sr', 'sr-Cyrl-ME', 'Serbisch (Kyrillisch, Montenegro)');
INSERT INTO static_languages_locals VALUES ('246', '0', '0', 'sr', 'sr-Cyrl-RS', 'Serbisch (Kyrillisch, Serbien)');
INSERT INTO static_languages_locals VALUES ('247', '0', '0', 'sr', 'sr-Latn', 'Serbisch (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('248', '0', '0', 'sr', 'sr-Latn-BA', 'Serbisch (Lateinisch, Bosnien und Herzegowina)');
INSERT INTO static_languages_locals VALUES ('249', '0', '0', 'sr', 'sr-Latn-ME', 'Serbisch (Lateinisch, Montenegro)');
INSERT INTO static_languages_locals VALUES ('250', '0', '0', 'sr', 'sr-Latn-RS', 'Serbisch (Lateinisch, Serbien)');
INSERT INTO static_languages_locals VALUES ('251', '0', '0', 'sv', 'sv-FI', 'Schwedisch (Finnland)');
INSERT INTO static_languages_locals VALUES ('252', '0', '0', 'sv', 'sv-SE', 'Schwedisch (Schweden)');
INSERT INTO static_languages_locals VALUES ('253', '0', '0', 'sw', 'sw-KE', 'Suaheli (Kenia)');
INSERT INTO static_languages_locals VALUES ('254', '0', '0', 'sw', 'sw-TZ', 'Suaheli (Tansania)');
INSERT INTO static_languages_locals VALUES ('255', '0', '0', 'ta', 'ta-IN', 'Tamilisch (Indien)');
INSERT INTO static_languages_locals VALUES ('256', '0', '0', 'ta', 'ta-LK', 'Tamilisch (Sri Lanka)');
INSERT INTO static_languages_locals VALUES ('257', '0', '0', 'te', 'te-IN', 'Telugu (Indien)');
INSERT INTO static_languages_locals VALUES ('258', '0', '0', 'th', 'th-TH', 'Thailändisch (Thailand)');
INSERT INTO static_languages_locals VALUES ('259', '0', '0', 'ti', 'ti-ER', 'Tigrinja (Eritrea)');
INSERT INTO static_languages_locals VALUES ('260', '0', '0', 'ti', 'ti-ET', 'Tigrinja (Äthiopien)');
INSERT INTO static_languages_locals VALUES ('261', '0', '0', 'to', 'to-TO', 'Tongaisch (Tonga)');
INSERT INTO static_languages_locals VALUES ('262', '0', '0', 'tr', 'tr-TR', 'Türkisch (Türkei)');
INSERT INTO static_languages_locals VALUES ('263', '0', '0', 'uk', 'uk-UA', 'Ukrainisch (Ukraine)');
INSERT INTO static_languages_locals VALUES ('264', '0', '0', 'ur', 'ur-IN', 'Urdu (Indien)');
INSERT INTO static_languages_locals VALUES ('265', '0', '0', 'ur', 'ur-PK', 'Urdu (Pakistan)');
INSERT INTO static_languages_locals VALUES ('266', '0', '0', 'uz', 'uz-Arab', 'Usbekisch (Arabisch)');
INSERT INTO static_languages_locals VALUES ('267', '0', '0', 'uz', 'uz-Arab-AF', 'Usbekisch (Arabisch, Afghanistan)');
INSERT INTO static_languages_locals VALUES ('268', '0', '0', 'uz', 'uz-Cyrl', 'Usbekisch (Kyrillisch)');
INSERT INTO static_languages_locals VALUES ('269', '0', '0', 'uz', 'uz-Cyrl-UZ', 'Usbekisch (Kyrillisch, Usbekistan)');
INSERT INTO static_languages_locals VALUES ('270', '0', '0', 'uz', 'uz-Latn', 'Usbekisch (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('271', '0', '0', 'uz', 'uz-Latn-UZ', 'Usbekisch (Lateinisch, Usbekistan)');
INSERT INTO static_languages_locals VALUES ('272', '0', '0', 'vai', 'vai-Latn', 'Vai-Sprache (Lateinisch)');
INSERT INTO static_languages_locals VALUES ('273', '0', '0', 'vai', 'vai-Latn-LR', 'Vai-Sprache (Lateinisch, Liberia)');
INSERT INTO static_languages_locals VALUES ('274', '0', '0', 'vai', 'vai-Vaii', 'Vai-Sprache (Vai)');
INSERT INTO static_languages_locals VALUES ('275', '0', '0', 'vai', 'vai-Vaii-LR', 'Vai-Sprache (Vai, Liberia)');
INSERT INTO static_languages_locals VALUES ('276', '0', '0', 'vi', 'vi-VN', 'Vietnamesisch (Vietnam)');
INSERT INTO static_languages_locals VALUES ('277', '0', '0', 'yo', 'yo-NG', 'Yoruba (Nigeria)');
INSERT INTO static_languages_locals VALUES ('278', '0', '0', 'zh', 'zh-Hans', 'Chinesisch (Vereinfacht)');
INSERT INTO static_languages_locals VALUES ('279', '0', '0', 'zh', 'zh-Hans-CN', 'Chinesisch (Vereinfacht, China)');
INSERT INTO static_languages_locals VALUES ('280', '0', '0', 'zh', 'zh-Hans-HK', 'Chinesisch (Vereinfacht, Sonderverwaltungszone Hongkong)');
INSERT INTO static_languages_locals VALUES ('281', '0', '0', 'zh', 'zh-Hans-MO', 'Chinesisch (Vereinfacht, Sonderverwaltungszone Macao)');
INSERT INTO static_languages_locals VALUES ('282', '0', '0', 'zh', 'zh-Hans-SG', 'Chinesisch (Vereinfacht, Singapur)');
INSERT INTO static_languages_locals VALUES ('283', '0', '0', 'zh', 'zh-Hant', 'Chinesisch (Traditionell)');
INSERT INTO static_languages_locals VALUES ('284', '0', '0', 'zh', 'zh-Hant-HK', 'Chinesisch (Traditionell, Sonderverwaltungszone Hongkong)');
INSERT INTO static_languages_locals VALUES ('285', '0', '0', 'zh', 'zh-Hant-MO', 'Chinesisch (Traditionell, Sonderverwaltungszone Macao)');
INSERT INTO static_languages_locals VALUES ('286', '0', '0', 'zh', 'zh-Hant-TW', 'Chinesisch (Traditionell, Taiwan)');
INSERT INTO static_languages_locals VALUES ('287', '0', '0', 'zu', 'zu-ZA', 'Zulu (Südafrika)');
